export const UPDATE_QUERY = 'APP_UPDATE_QUERY';

export const EXECUTE_QUERY = 'APP_EXECUTE_QUERY';
export const ON_EXECUTE_QUERY_START = 'APP_ON_EXECUTE_QUERY_START';
export const ON_EXECUTE_QUERY_END = 'APP_ON_EXECUTE_QUERY_END';
export const ON_EXECUTE_QUERY_ERROR = 'APP_ON_EXECUTE_QUERY_ERROR';

export const RESET_STATE = 'APP_RESET_STATE';
